---
Name: loginfiles
After:
    - "#assetscore"
---
SilverStripe\Core\Injector\Injector:
    SilverStripe\Assets\Storage\AssetStore:
        class: 'WebbuildersGroup\LoginFiles\Flysystem\FlysystemAssetStore'
